import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Motus Research" },
      { name: "description", content: "Terms of Service for Motus Research AI chat platform." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="relative min-h-screen bg-black text-white">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[400px] grid-bg opacity-40" />
      <div className="pointer-events-none absolute left-1/2 top-[-200px] h-[400px] w-[600px] -translate-x-1/2 rounded-full bg-[oklch(0.55_0.22_295/0.15)] blur-[140px]" />

      <header className="relative z-20 mx-auto flex max-w-4xl items-center gap-4 px-6 py-6">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-zinc-400 transition hover:text-white">
          <ArrowLeft className="h-4 w-4" /> Back
        </Link>
      </header>

      <article className="relative z-10 mx-auto max-w-4xl px-6 pb-24">
        <h1 className="font-display text-4xl font-bold tracking-tight md:text-5xl">Terms of Service</h1>
        <p className="mt-3 text-sm text-zinc-500">Last updated: June 30, 2025</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-zinc-400">
          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">1. Acceptance of Terms</h2>
            <p>By accessing or using Motus Research ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">2. Eligibility</h2>
            <p>You must be at least 18 years old to use Motus Research. By using the Platform, you represent and warrant that you meet this age requirement.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">3. Account Responsibilities</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must not share your account or allow unauthorized access.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">4. Acceptable Use</h2>
            <p>While Motus Research provides an unfiltered AI experience, you agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Use the Platform for any illegal activity.</li>
              <li>Attempt to exploit, hack, or disrupt the Platform's infrastructure.</li>
              <li>Generate content involving real individuals without their consent.</li>
              <li>Use the Platform to harass, threaten, or harm others.</li>
              <li>Redistribute or resell access to the Platform without authorization.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">5. Content & AI Interactions</h2>
            <p>AI-generated content on Motus Research is fictional and should not be treated as factual, professional, or legal advice. You acknowledge that:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>AI responses are generated by language models and may be inaccurate.</li>
              <li>You are solely responsible for how you use AI-generated content.</li>
              <li>Motus Research does not endorse or verify any AI-generated output.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">6. Imported Bots</h2>
            <p>When importing bots from third-party platforms (e.g., Chai), you acknowledge that bot definitions and characters may be subject to their original creators' rights. Motus Research is not responsible for third-party bot content.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">7. Service Availability</h2>
            <p>We strive to keep the Platform available but do not guarantee uninterrupted access. We reserve the right to modify, suspend, or discontinue any part of the service at any time.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">8. Limitation of Liability</h2>
            <p>Motus Research is provided "as is" without warranties of any kind. To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the Platform.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">9. Termination</h2>
            <p>We may suspend or terminate your account at our discretion if you violate these terms. Upon termination, your right to use the Platform ceases immediately.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">10. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">11. Contact</h2>
            <p>Questions? Reach out via our Discord or email us at <span className="text-[oklch(0.75_0.25_300)]">support@motus-research.xyz</span>.</p>
          </section>
        </div>
      </article>
    </main>
  );
}
